name: arm64-macos-clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    timeout-minutes: 10
    runs-on: macos-15
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DTMC_USE_HWLOC=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS='-Werror -fexperimental-library' -B build/${{matrix.BUILD_TYPE}} .
    - name: build
      run: cmake --build build/${{matrix.BUILD_TYPE}} --parallel $(sysctl -n hw.logicalcpu) --target tests
    - name: run tests
      run: ./build/${{matrix.BUILD_TYPE}}/tests/tests
